# Generated by Django 5.1 on 2024-08-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='open_mic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('start_time', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=100)),
                ('ig_link', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10)),
                ('frequency', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('notes', models.TextField(max_length=500)),
            ],
        ),
    ]
