# Generated by Django 5.1 on 2024-08-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedy_app', '0002_alter_open_mic_address_alter_open_mic_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_mic',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='open_mic',
            name='ig_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='open_mic',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='open_mic',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
