# Generated by Django 5.1 on 2024-10-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedy_app', '0003_alter_open_mic_address_alter_open_mic_ig_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_mic',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
